######################################################################
##
## Filename: uart_baud_gen.udo
## Created on: Mon May 03 05:22:58 Arab Standard Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
